name: ğŸ‰ Release Notify

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Release Notify
        uses: visiky/dingtalk-release-notify@main
        with:
          DING_TALK_TOKEN: ${{ secrets.DINGTALK_ROBOT_TOKEN }}
          notify_title: 'ğŸ‰ AVA æ–°ç‰ˆæœ¬å‘å¸ƒ {release_tag} ğŸ‰'
          notify_body: '## { title }<hr /> ![preview](https://gw.alipayobjects.com/zos/antfincdn/IUEpmsGeBj/AVA-publish-success.png) <hr /> { body } <hr />'
          notify_footer: '> å‰å¾€ [**AntV/AVA Releases**]({ release_url }) æŸ¥çœ‹å®Œæ•´ä¿¡æ¯'
          at_all: false
          enable_prerelease: true
