name: üîÅ Sync After Auto Release

# Sync Package.json and CHANGELOG After Auto Release
on:
  push:
    branches:
      - alpha

jobs:
  sync:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'alpha'

      - name: Git bootstrap
        run: |
          git config --global user.name 'pddpd'
          git config --global user.email 'pddpengdi@gmail.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Create PR
        run: |
          gh pr create --title "chore: update package.json and CHANGELOG" --body "ü§ñ Create by [[Sync After Auto Release](https://github.com/antvis/AVA/blob/master/.github/workflows/sync-after-auto-release.yml)]."
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
